server:
  port: 20104

spring:
  application:
    name: dynamictp

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false